services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    restart: always
 
  api:
    build: ./api
    ports:
     - '5001:5001'
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
 
  adminer:
    image: adminer
    ports:
      - '8000:8080'
    restart: always
 