name: CI_time

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.19.3']

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install Nodejs #{{matrix.node-version}} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
